var CLIENT_ID="109625613373-ajtdrbojqhcinjhu0slmjo6k8smks0ru.apps.googleusercontent.com",SCOPES="https://www.googleapis.com/auth/drive.appdata",backupStart=!1;function handleClientLoad(){window.setTimeout(checkAuth,1)}function checkAuth(){gapi.auth.authorize({client_id:CLIENT_ID,scope:SCOPES,immediate:!0},handleAuthResult)}
function handleAuthResult(a){a&&!a.error?($("#authorizeDiv").hide(),gapi.client.load("drive","v2",function(){listBackup()})):($("#authorizeButton").click(manualAuth),$("#authorizeDiv").show(),$("#backupList").empty())}function manualAuth(){gapi.auth.authorize({client_id:CLIENT_ID,scope:SCOPES,immediate:!1},handleAuthResult);$("#authorizeButton").val(getMessage("reloadAuth")).unbind("click",manualAuth).click(function(){location.reload()})}
function listBackup(){var a=gapi.client.drive.files.list({q:"'appdata' in parents"}),f=$("#backupList").empty();a.execute(function(a){var b=0,e;for(e in a.items){var c=a.items[e],h=new Date(c.modifiedDate),d=$("<div>",{"class":"backupItem",id:c.id}).appendTo(f);c.title.indexOf("toomanytabs.json")<0||(b++,$("<label>",{text:(c.description?"["+c.description+"] ":"")+getMessage("backupSaveAt")+" "+h.toLocaleDateString()+" "+h.toLocaleTimeString()}).appendTo(d),$("<input>",{type:"button",value:"Restore",
downloadUrl:c.downloadUrl,click:function(){restoreBackup($(this).attr("downloadUrl"))}}).appendTo(d),$("<input>",{type:"button",value:getMessage("remove"),itemId:c.id,click:function(){removeBackup($(this).attr("itemId"))}}).appendTo(d),$("<input>",{type:"button",value:"View",itemId:c.id,downloadUrl:c.downloadUrl,ts:c.modifiedDate,click:function(){viewBackup($(this))}}).appendTo(d))}b==0&&(d=$("<div>",{"class":"backupItem",text:getMessage("backupNotFound")}).appendTo(f));$("<input>",{type:"button",
value:getMessage("backupNow"),click:function(){$("<img>",{src:"/img/ajax-loader.gif","class":"ajax-icon"}).appendTo("#backupList");$("<span>",{"class":"backupItem",text:getMessage("backupAdding")}).appendTo("#backupList");backupStart=!0;background.prepareBackup(!0)}}).appendTo(f)})}function backupComplete(){backupStart&&(alert(getMessage("backupSuccess")),backupStart=!1);listBackup()}
function viewBackup(a){$(".backupItem").css("font-weight","normal");var f=a.attr("downloadUrl"),g=new Date(a.attr("ts")),b=a.attr("itemId");if(f)a=gapi.auth.getToken().access_token,$.ajax(f,{headers:{Authorization:"Bearer "+a}}).done(function(a){console.log(JSON.stringify(a));a=formatData(a,g);$("#backupText").val(a).show();$("#"+b).css("font-weight","bold")}).fail(function(a,c,b){console.error(c,b);alert(getMessage("formatError"))})}
function formatData(a,f){var g=a.rowDataMap,b;for(b in g)if(!(g[b].id==1||g[b].id==2)){var e=[],c=g[b].tabs,h;for(h in c)try{var d=c[h];e.push({title:d.title,URL:[d.URL.pop()],pinned:d.pinned,favIconURL:d.favIconURL})}catch(i){console.error(i)}g[b].tabs=e}e="TooManyTabs Backup at "+f.toLocaleDateString()+" "+f.toLocaleTimeString()+"\n";for(b in g)for(h in e+="\n"+g[b].name+" ("+g[b].tabs.length+") \n",c=g[b].tabs,c)try{d=c[h],e+="    "+d.title+"\n",e+="        "+d.URL[0]+"\n"}catch(j){console.error(j)}return e}
function restoreBackup(a){if(confirm(getMessage("importDescription2"))&&a){var f=gapi.auth.getToken().access_token;$.ajax(a,{headers:{Authorization:"Bearer "+f}}).done(function(a){importData(a)}).fail(function(a,b,e){console.error(b,e);alert(getMessage("formatError"))})}}
function importData(a){beforeImport();if(!a||!a.rowDataMap[0]||a.rowDataMap[0].id!=0||!a.rowDataMap[3]||a.rowDataMap[3].id!=3)return console.log("Inconsistent column data"),alert(getMessage("formatError")),null;background||(background=chrome.extension.getBackgroundPage());localStorage.rowDataMap=JSON.stringify(a.rowDataMap);if(importData.currentRowId)localStorage.currentRowId=a.currentRowId;background.afterImport(a.usageMode);alert(getMessage("importedSuccessfully"))}
function removeBackup(a){confirm(getMessage("areYouSure"))&&gapi.client.drive.files["delete"]({fileId:a}).execute(function(){alert(getMessage("backupRemoved"));listBackup()})}function setApplicationDataFolderMetadata(){gapi.client.drive.files.get({fileId:"appdata"}).execute(function(a){localStorage.appdataId=a.id;console.log("Id: "+a.id);console.log("Title: "+a.title)})}
$(document).ready(function(){$("#driveProfile").val(localStorage.backupfileDesc||"").change(function(){var a=$(this).val().trim();a?localStorage.backupfileDesc=a:delete localStorage.backupfileDesc})});
