// Generated by CoffeeScript 1.10.0
(function() {
  var init, settings, toggle;

  settings = chrome.extension.getBackgroundPage().syntaxtic.settings;

  init = function() {
    return chrome.tabs.getSelected(null, function(tab) {
      var blacklist, box, checkboxes, i, len, results;
      checkboxes = document.querySelectorAll('.clicker');
      results = [];
      for (i = 0, len = checkboxes.length; i < len; i++) {
        box = checkboxes[i];
        blacklist = settings[box.id + "Blacklist"];
        box.addEventListener('click', toggle);
        results.push(box.checked = blacklist.indexOf(tab.url) === -1);
      }
      return results;
    });
  };

  toggle = function(e) {
    chrome.tabs.getSelected(null, function(tab) {
      var blacklist, idx;
      blacklist = settings[e.target.id + "Blacklist"];
      if (e.target.checked) {
        idx = blacklist.indexOf(tab.url);
        if (idx !== -1) {
          blacklist.splice(idx, 1);
        }
      } else {
        blacklist.push(tab.url);
      }
      return settings[e.target.id + "Blacklist"] = blacklist;
    });
    return chrome.tabs.executeScript(null, {
      file: "toggle_" + e.target.id + ".js"
    });
  };

  document.addEventListener('DOMContentLoaded', function() {
    return init();
  });

}).call(this);
