// Generated by CoffeeScript 1.10.0
(function() {
  var toggle_hilight;

  toggle_hilight = function() {
    var i, len, ref, results, stylesheet;
    ref = document.styleSheets;
    results = [];
    for (i = 0, len = ref.length; i < len; i++) {
      stylesheet = ref[i];
      if (stylesheet.href && stylesheet.href.match(/.*shTheme[a-zA-Z]*\.css/)) {
        results.push(stylesheet.disabled = !stylesheet.disabled);
      } else {
        results.push(void 0);
      }
    }
    return results;
  };

  toggle_hilight();

}).call(this);
